oeo-model:
 - src/ontology/edits/oeo-model.omn

oeo-physical:
 - src/ontology/edits/oeo-physical.omn

oeo-social:
 - src/ontology/edits/oeo-social.omn
 
 external ontology:
  - src/ontology/modules/*
