dist: bionic
sudo: false
language: python

before_script:
  - mkdir $TRAVIS_BUILD_DIR/.logs
  - pip install robotframework

script:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - robot validate-profile --input src/ontology/oeo.omn --profile Full -vvv --output merged-validation.txt > .logs/validate.txt
  - robot verify --input src/ontology/edits/oeo-physical.omn --queries tests/verify/*

after_failure:
  - more .log/* | cat