dist: bionic
sudo: false
language: python

before_script:
  pip install robotframework

script:
  robot validate-profile --input src/ontology/oeo.omn --profile Full -vvv --output merged-validation.txt > .logs/validate.txt

after_failure:
  - more .log/* | cat