dist: bionic
language: java

before_script:
  - mkdir $TRAVIS_BUILD_DIR/.logs
  - mkdir lib
  - mkdir bin
  - wget https://github.com/ontodev/robot/releases/download/v1.6.0/robot.jar > lib/robot
  - curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > lib/robot
  - ln -s lib/robot bin/robot
  - chmod u+x lib/robot
  - LOCAL_BIN=`pwd`/bin
  - export PATH="$LOCAL_BIN:$PATH"

script:
  - cd $TRAVIS_BUILD_DIR
  - robot validate-profile --input src/ontology/oeo.omn --profile Full -vvv --output merged-validation.txt > .logs/validate.txt
  - robot verify --input src/ontology/edits/oeo-physical.omn --queries tests/verify/*

after_failure:
  - more .log/* | cat