dist: bionic
language: java

before_script:
  - mkdir $TRAVIS_BUILD_DIR/.logs
  - mkdir lib
  - wget https://github.com/ontodev/robot/releases/download/v1.6.0/robot.jar -O lib/robot.jar
  - TRAVIS_BASE=`pwd`
 
script:
  - alias robot="java -jar $TRAVIS_BASE/lib/robot.jar"
  - alias
  - cd $TRAVIS_BUILD_DIR
  - robot validate-profile --input src/ontology/oeo.omn --profile Full -vvv --output merged-validation.txt > .logs/validate.txt
  - robot verify --input src/ontology/edits/oeo-physical.omn --queries tests/verify/*

after_failure:
  - more .log/* | cat