dist: bionic
sudo: false
language: python

before_script:
  - mkdir .logs
  - pip install robotframework

script:
  - robot validate-profile --input $TRAVIS_BUILD_DIR/src/ontology/oeo.omn --profile Full -vvv --output merged-validation.txt > .logs/validate.txt

after_failure:
  - more .log/* | cat