name: RemoveToDoLabel

on:
  project_card:

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: remove to do label
        uses: andymckay/labeler@master
        with:
          remove-labels: "To do"
